services:
  crud_x-ray:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: crud_x-ray
    image: common/crud_x-ray:1.0.0
    restart: always
    environment:
      - NODE_ENV=development
      - RABBITMQ_CONNECTION=amqp://guest:guest@rabbitmq:5672
      - DataBase=mongo
      - mongodb_database=mng_x-ray
      - mongodb_addr=mongodb://mongo:27017
      - mongodb_username=
      - mongodb_password=
      - mongodb_timeout=30
      - http_port=3000
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - company_network

networks:
  company_network:
    name: company_network



